@extends('layouts.apps')

@section('content')
    <!-- <div class="container">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="row justify-content-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="col-md-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="card-header">Dashboard</div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="card-body">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @if (session('status'))
    <div class="alert alert-success" role="alert">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {{ session('status') }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
    @endif

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    You are logged in!
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div> -->
    <div class="d-flex flex-row justify-content-center mt-5 p-5">
        <div class="card my-5 bg-light p-5">
            <div class="card-title">
                <h1 class="mb-5">Add Employee</h1>
                <div class="progress">
                    <div class="progress-bar" role="progressbar" style="width: 100%; background-color:#EEB266;"
                        aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
            </div>
            <div class="card-body">
                <form action="/employee/form3" method="POST" class="d-flex flex-column gap-4">
                    @csrf
                    <div class="row g-xl-5">
                        <div class="col">
                            <label for="join_date" class="form-label fs-2">Date of Join</label>
                            <input value="{{ optional($sessions)['join_date'] }}" type="date"
                                class="form-control fs-5  @error('join_date') is-invalid @enderror"
                                style="background-color:#EEB26626" id="join_date" placeholder="Join of Date"
                                name="join_date">
                            @error('birth_date')
                                <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="col">
                            <label for="study" class="form-label fs-2">Study</label>
                            <select class="form-control fs-5  @error('study') is-invalid @enderror"
                                style="background-color:#EEB26626" study" placeholder="Choose District" name="study">
                                <option value="smp">SMP</option>
                                <option value="sma">SMA/SMK</option>
                                <option value="s1">Strata 1</option>
                                <option value="s2">Strata 2</option>
                                <option value="s3">Strata 3</option>
                            </select>
                            @error('study')
                                <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="row g-xl-5">
                        <div class="col">
                            <label for="status" class="form-label fs-2">Status</label>
                            <select class="form-control fs-5  @error('status') is-invalid @enderror"
                                style="background-color:#EEB26626" id="status" placeholder="Choose City" name="status">
                                <option value="office">Office</option>
                                <option value="home">Home</option>
                            </select>
                            @error('status')
                                <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="col">
                            <label for="marriage_status" class="form-label fs-2">Marriage Status</label>
                            <select class="form-control fs-5  @error('marriage_status') is-invalid @enderror"
                                style="background-color:#EEB26626" id="marriage_status" placeholder="Choose Status"
                                name="marriage_status">
                                <option value="married">Menikah</option>
                                <option value="single">Lajang</option>
                                <option value="disvorce">Cerai</option>
                            </select>
                            @error('marriage_status')
                                <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="row g-xl-5">
                        <div class="col">
                            <label for="account_bank" class="form-label fs-2">Account Bank</label>
                            <select class="form-control fs-5  @error('account_bank') is-invalid @enderror"
                                style="background-color:#EEB26626" id="account_bank" placeholder="Choose Status"
                                name="province">
                                <option value="bca">BCA</option>
                                <option value="bni">BNI</option>
                                <option value="bri">BRI</option>
                                <option value="mandiri">Mandiri</option>
                            </select>
                            @error('account_bank')
                                <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="col">
                            <label for="account_name" class="form-label fs-2">Account Name</label>
                            <input value="{{ optional($sessions)['account_name'] }}" type="text"
                                class="form-control fs-5  @error('account_name') is-invalid @enderror"
                                style="background-color:#EEB26626" id="account_name" placeholder="Account Name"
                                name="account_name">
                            @error('account_name')
                                <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="row g-xl-5">
                        <div class="col">
                            <label for="account_number" class="form-label fs-2">Account Number</label>
                            <input value="{{ optional($sessions)['account_number'] }}" type="text"
                                class="form-control fs-5  @error('account_number') is-invalid @enderror"
                                style="background-color:#EEB26626" id="account_number" name="account_number"
                                placeholder="Account Number">
                            @error('account_number')
                                <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="col">
                            <label for="salary" class="form-label fs-2">Salary</label>
                            <input value="{{ optional($sessions)['salary'] }}" type="text"
                                class="form-control fs-5  @error('salary') is-invalid @enderror"
                                style="background-color:#EEB26626" id="salary" name="salary" placeholder="Salary">
                            @error('salary')
                                <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
            </div>
            <div class="d-flex flex-row justify-content-center gap-5">
                <a href="/previous-form2"><button type="button"
                        class="btn btn-light border-warning btn-lg">Previous</button></a>
                <button type="submit" class="btn btn-warning btn-lg text-light">Submit</button>
            </div>
            </form>
        </div>
    </div>
    </div>
@endsection
