@extends('layouts.apps')

@section('content')
    <!-- <div class="container">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="row justify-content-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="col-md-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="card-header">Dashboard</div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="card-body">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @if (session('status'))
    <div class="alert alert-success" role="alert">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {{ session('status') }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
    @endif

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            You are logged in!
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div> -->
    <div class="d-flex flex-row justify-content-center mt-5 p-5">
        <div class="card my-5 bg-light p-5">
            <div class="card-title">
                <h1 class="mb-5">Edit Employee</h1>
                <div class="progress">
                    <div class="progress-bar" role="progressbar" style="width: 75%; background-color:#EEB266;"
                        aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
            </div>
            <div class="card-body">
                <form action="/edit-employee/form2" method="POST" class="d-flex flex-column gap-4">
                    @csrf
                    <div class="row g-xl-5">
                        <div class="col">
                            <label for="address" class="form-label fs-2">Address</label>
                            <input
                                value="{{ optional($sessions)['address'] ? optional($sessions)['address'] : $employees->alamat }}"
                                type="text" class="form-control fs-5 @error('address') is-invalid @enderror"
                                style="background-color:#EEB26626" id="address" name="address" placeholder="Address">
                            @error('address')
                                <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="col">
                            <label for="district" class="form-label fs-2">District</label>
                            <select class="form-control fs-5  @error('district') is-invalid @enderror"
                                style="background-color:#EEB26626" id="city" placeholder="Choose District"
                                name="district">
                                @foreach ($districts as $district)
                                    <option value={{ $district->id }}>{{ $district->name }}</option>
                                @endforeach
                            </select>
                            @error('district')
                                <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="row g-xl-5">
                        <div class="col">
                            <label for="city" class="form-label fs-2">City</label>
                            <select class="form-control fs-5  @error('city') is-invalid @enderror"
                                style="background-color:#EEB26626" id="city" placeholder="Choose City" name="city">
                                @foreach ($regencies as $regency)
                                    <option value={{ $regency->id }}>{{ $regency->name }}</option>
                                @endforeach
                            </select>
                            @error('city')
                                <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="col">
                            <label for="province" class="form-label fs-2">Province</label>
                            <select class="form-control fs-5  @error('province') is-invalid @enderror"
                                style="background-color:#EEB26626" id="province" placeholder="Choose Province"
                                name="province">
                                @foreach ($provinces as $province)
                                    <option value={{ $province->id }}>{{ $province->name }}</option>
                                @endforeach
                            </select>
                            @error('province')
                                <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="row g-xl-5">
                        <div class="col">
                            <label for="phone" class="form-label fs-2">Phone</label>
                            <input
                                value="{{ optional($sessions)['phone'] ? optional($sessions)['phone'] : $employees->hp }}"
                                type="text" class="form-control fs-5  @error('phone') is-invalid @enderror"
                                style="background-color:#EEB26626" id="phone" name="phone" placeholder="Phone Number">
                            @error('phone')
                                <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="col">
                            <label for="postal_code" class="form-label fs-2">Postal Code</label>
                            <input
                                value="{{ optional($sessions)['postal_code'] ? optional($sessions)['postal_code'] : $employees->kode_pos }}"
                                type="text" class="form-control fs-5  @error('postal_code') is-invalid @enderror"
                                style="background-color:#EEB26626" id="postal_code" placeholder="Postal Code"
                                name="postal_code">
                            @error('postal_code')
                                <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="row g-xl-5">
                        <div class="col">
                            <label for="emergency_name" class="form-label fs-2">Emergency Contact</label>
                            <input
                                value="{{ optional($sessions)['emergency_name'] ? optional($sessions)['emergency_name'] : $employees->kontak_darurat }}"
                                type="text" class="form-control fs-5  @error('emergency_name') is-invalid @enderror"
                                style="background-color:#EEB26626" id="emergency_name" name="emergency_name"
                                placeholder="Emergency contact name">
                            @error('emergency_name')
                                <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="col">
                            <label for="emergency_contact" class="form-label fs-2">Emergency Phone</label>
                            <input
                                value="{{ optional($sessions)['emergency_contact'] ? optional($sessions)['emergency_contact'] : $employees->hp_darurat }}"
                                type="text" class="form-control fs-5  @error('emergency_contact') is-invalid @enderror"
                                style="background-color:#EEB26626" id="emergency_contact" name="emergency_contact"
                                placeholder="Phone Number">
                            @error('emergency_contact')
                                <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
            </div>
            <div class="d-flex flex-row justify-content-center gap-5">
                <a href="/previous-editForm1/{{ $employees->id }}"><button type="button"
                        class="btn btn-light border-warning btn-lg">Previous</button></a>
                <button type="submit" class="btn btn-warning btn-lg text-light">Next</button>
            </div>
            </form>
        </div>
    </div>
    </div>
@endsection
