@extends('layouts.apps')

@section('content')
    <!-- <div class="container">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="row justify-content-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="col-md-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="card-header">Dashboard</div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="card-body">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @if (session('status'))
    <div class="alert alert-success" role="alert">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {{ session('status') }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
    @endif

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            You are logged in!
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div> -->
    <div class="d-flex flex-row justify-content-center mt-5 p-5">
        <div class="card my-5 bg-light p-5">
            <div class="card-title">
                <h1 class="mb-5">Edit Job Title</h1>
                <div class="progress">
                    <div class="progress-bar" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0"
                        aria-valuemax="100"></div>
                </div>
            </div>
            <div class="card-body">
                <form action="/update-job-title/{{ $jobTitles->id }}" method="POST" class="d-flex flex-column gap-4">
                    @csrf
                    @method('PATCH')
                    <div class="row g-3">
                        <div class="col-12">
                            <label for="division_code" class="form-label fs-2">Division Code</label>
                            <select class="form-control fs-5  @error('division_code') is-invalid @enderror"
                                style="background-color:#EEB26626" id="department_code" name="division_code"
                                placeholder="Choose Department">
                                @foreach ($divisions as $division)
                                    <option value={{ $division->id }}
                                        {{ $division->id == $jobTitles->division->id ? 'selected' : '' }}>
                                        {{ $division->kode }} -
                                        {{ $division->nama }}
                                    </option>
                                @endforeach
                            </select>
                            @error('division_code')
                                <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="col-12">
                            <label for="job_code" class="form-label fs-2">Job Title Code</label>
                            <input value="{{ $jobTitles->kode }}" type="text" style="background-color:#EEB26626"
                                class="form-control fs-5 @error('job_code') is-invalid @enderror" id="job_code"
                                placeholder="Job title code" name="job_code">
                        </div>
                        <div class="col-12">
                            <label for="job_name" class="form-label fs-2">Job Title Name</label>
                            <input value="{{ $jobTitles->nama }}" type="text" style="background-color:#EEB26626"
                                class="form-control fs-5 @error('job_name') is-invalid @enderror" id="job_name"
                                placeholder="Job title name" name="job_name">
                        </div>
                        <div class="col-12 form-switch">
                            <label for="status" class="form-label fs-2" for="status">Job Title Status</label>
                            <div class="row">
                                <div class="col-2">
                                    <label for="" class="form-control-plaintext fs-4">Inactive</label>
                                </div>
                                <div class="col-2">
                                    <input value={{ $jobTitles->status == 0 ? '1' : 0 }} name="status"
                                        style="background-color: #EEB26626" class="form-check-input w-50" type="checkbox"
                                        role="switch" id="status">
                                </div>
                                <div class="col-2">
                                    <label for="" class="form-control-plaintext fs-4">Active</label>
                                </div>
                            </div>
                        </div>
                        <div class="row-3">
                            <div class="col-12">
                                <label for="description" class="form-label fs-2">Description</label>
                                <textarea name="description" type="text" style="background-color: #EEB26626;"
                                    class="form-control fs-4
                                    @error('description') is-invalid @enderror"
                                    id="inputAddress" rows="10" cols="10" placeholder="Job Title Description">{{ $jobTitles->keterangan }}</textarea>
                                @error('description')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                    </div>
            </div>
            <div class="d-flex flex-row justify-content-center gap-5">
                <a href="/division"><button type="button" class="btn btn-light border-warning btn-lg">Cancel</button></a>
                <button type="submit" class="btn btn-warning btn-lg">Confirm</button>
            </div>
            </form>
        </div>
    </div>
    </div>
@endsection
